# Generated by Django 4.2.3 on 2023-08-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password1', models.CharField(default='default_password', max_length=255)),
                ('password2', models.CharField(default='default_password', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
