# Generated by Django 4.2.3 on 2023-08-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDoList', '0003_rename_password1_member_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='firstName',
            new_name='first_name',
        ),
    ]
