# Generated by Django 4.2.3 on 2023-08-07 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDoList', '0008_sharednote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='shared_with',
        ),
    ]
