# Generated by Django 4.2.3 on 2023-08-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDoList', '0010_usersharednote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSharedNote',
        ),
    ]
