# Generated by Django 4.2.3 on 2023-08-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoList', '0012_note_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
